export enum EventCategory {
  FASHION = 'Fashion & Beauty',
  BUSINESS = 'Business & Professional',
  TECHNOLOGY = 'Technology',
  HEALTH = 'Health & Wellness',
  MUSIC = 'Music',
  ART = 'Art & Culture',
  EDUCATION = 'Education & Learning',
  SPORTS = 'Sports & Fitness',
  TRAVEL = 'Travel & Adventure',
  FOOD = 'Food & Drink',
  CHARITY = 'Charity & Causes',
  FILM = 'Film & Media',
  FAMILY = 'Family & Kids',
  GOVERNMENT = 'Government & Politics',
  RELIGION = 'Religion & Spirituality',
  SCIENCE = 'Science & Innovation',
  AUTOMOTIVE = 'Automotive',
  HOBBIES = 'Hobbies & Special Interests',
  FESTIVALS = 'Festivals & Fairs',
  SOCIAL = 'Social & Networking',
  OTHERS = 'Others',
}
