name: Update API Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download the Latest API Specification from Stoplight
      run: curl -o docs/openapi.yaml https://eventful-api.stoplight.io/docs/eventful/702712f52dede-eventful-api

    - name: Commit and Push if Changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add docs/openapi.yaml
        git commit -m "Update OpenAPI documentation" || echo "No changes to commit"
        git push
